model_list:
- model_name: claude-3-sonnet
  litellm_params:
    model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0
    max_tokens: 4000
    temperature: 0.5

- model_name: claude-3-haiku
  litellm_params:
    model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
    max_tokens: 4000
    temperature: 0.5
litellm_settings:
  modify_params: True
    